### ISSUE TITLE
Encrypted random factors

### ISSUE THREAD

**Issue by jaspervann** [OpenMined/PyPSI#9]
I know this implementation just follows the definition of the algorithm as outlined in the paper, but I am wondering why the random factors on the client side are encrypted. Why is the client set not just blinded by the random factors directly, then signed by the server and finally unblinded by the client? I expected that to be possible too, due to the partial homomorphic property of RSA, or am I missing something?

**Comment by youben11** [comment]
In the online phase, you can see that the server is computing `B = A ^ d mod N`, and A is actually `y * r ^ e` so `B = y ^ d * r` and when multiplied with the inverse it becomes `B * r_inv = y ^ d` and now we can compare the x (which were put into the bloom filter) and y elements since they are all raised to the power of d.

**Comment by jaspervann** [comment]
I see. Thank you!
